---
title: "Patient mIDH treated with mIDHi, DNA methylation analysis"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(ChAMP)
  library(GenomicRanges)
  library(FactoMineR)
  library(factoextra)
  library(sva)
  library(gridExtra)
  library(grid)
})

"%ni%" <- Negate("%in%")
```

```{r}
pheno <- read.csv("/media/alexis/DATA/Koichi_methylation_dat/samplesheet.csv")

BMIQ_norm_Koichi_samples <- readRDS("/media/alexis/DATA/Koichi_methylation_dat/BMIQ_norm_Koichi_samples.Rdata")

Control_sample <- colnames(BMIQ_norm_Koichi_samples)[colnames(BMIQ_norm_Koichi_samples) %ni% pheno$Sample]
Control_df <- data.frame("Sample" = Control_sample, "Pheno" = rep("Control", 8))
pheno <- rbind(pheno, Control_df) %>% dplyr::filter(Sample != "") %>% unique()
```




```{r}
Baseline_Sample <- pheno[stringr::str_detect(pheno$Pheno, "Baseline"), "Sample"]
Post_response_Sample <- pheno[stringr::str_detect(pheno$Pheno, "Post_treatment"), "Sample"]
Good_responder_Sample <- pheno[stringr::str_detect(pheno$Pheno, "CR") | stringr::str_detect(pheno$Pheno, "CRi"), "Sample"]
Bad_responder_Sample <- pheno[stringr::str_detect(pheno$Pheno, "PD") | stringr::str_detect(pheno$Pheno, "SD"), "Sample"]
IDH1_Sample <- pheno[stringr::str_detect(pheno$Pheno, "IDH1") & !stringr::str_detect(pheno$Pheno, "IDH1_IDH2"), "Sample"]
IDH2_Sample <- pheno[stringr::str_detect(pheno$Pheno, "IDH2") & !stringr::str_detect(pheno$Pheno, "IDH1_IDH2"), "Sample"]
Control_Sample <- pheno[stringr::str_detect(pheno$Pheno, "Control"), "Sample"]

pheno$Time <- ifelse(stringr::str_detect(pheno$Pheno, "Baseline"), "Baseline", ifelse(stringr::str_detect(pheno$Pheno, "Control"), "Control", "Relapse"))
pheno$Response <- ifelse(stringr::str_detect(pheno$Pheno, "CR") | stringr::str_detect(pheno$Pheno, "CRi"), "R", 
                         ifelse(stringr::str_detect(pheno$Pheno, "PD") | stringr::str_detect(pheno$Pheno, "SD"), "NR", 
                                ifelse(stringr::str_detect(pheno$Pheno, "Control"), "Control", "OR")))
```

############### PCA

```{r}
pca_DNA_meth <- prcomp(t(BMIQ_norm_Koichi_samples))

Global_pheno <- paste(pheno$Time, pheno$Response, sep = ".")

pca_Responses <- fviz_pca_ind(pca_DNA_meth, label="none", habillage=Global_pheno,
             addEllipses=TRUE, ellipse.level=0.95, title = "Combined Patients DNA meth pca")
print(pca_Responses)
```

```{r}
DMR_DMP_analysis <- function(DNA_meth_data, samples, factor){
  dat <- DNA_meth_data[,colnames(DNA_meth_data) %in% samples]
  
  DMP <- champ.DMP(dat, pheno = factor, arraytype = "EPIC")
  DMR <- champ.DMR(dat, pheno = factor, cores = 12, arraytype = "EPIC")
  GSEA <- champ.GSEA(beta = dat, DMP = DMP, DMR = DMR, cores = 12, pheno = factor, arraytype = "EPIC")
  return(list(DMP, DMR, GSEA))
}
```



############ GOOD Baseline vs Control

```{r}
Good_baseline_Control <- c(intersect(Good_responder_Sample, Baseline_Sample), Control_Sample)
Factor_Good_Baseline_Control <- colnames(BMIQ_norm_Koichi_samples)[colnames(BMIQ_norm_Koichi_samples) %in% Good_baseline_Control]
Factor_Good_Baseline_Control <- ifelse(Factor_Good_Baseline_Control %in% Good_responder_Sample, "Good_Responder_Baseline", "Control")

Good_Baseline_vs_Control <- DMR_DMP_analysis(BMIQ_norm_Koichi_samples, Good_baseline_Control, Factor_Good_Baseline_Control)

```

############ Bad Baseline vs Control

```{r}
Bad_baseline_Control <- c(intersect(Bad_responder_Sample, Baseline_Sample), Control_Sample)
Factor_Bad_Baseline_Control <- colnames(BMIQ_norm_Koichi_samples)[colnames(BMIQ_norm_Koichi_samples) %in% Bad_baseline_Control]
Factor_Bad_Baseline_Control <- ifelse(Factor_Bad_Baseline_Control %in% Bad_responder_Sample, "Bad_Responder_Baseline", "Control")

Bad_Baseline_vs_Control <- DMR_DMP_analysis(BMIQ_norm_Koichi_samples, Bad_baseline_Control, Factor_Bad_Baseline_Control)
```


############ GOOD vs BAD RESPONDER AT BASELINE

```{r}
Good_Bad_Baseline_sample <- intersect(c(Good_responder_Sample, Bad_responder_Sample), Baseline_Sample)
Factor_Good_Bad_Baseline <- colnames(BMIQ_norm_Koichi_samples)[colnames(BMIQ_norm_Koichi_samples) %in% Good_Bad_Baseline_sample]
Factor_Good_Bad_Baseline <- ifelse(Factor_Good_Bad_Baseline %in% Good_responder_Sample, "Good_Responder", "Bad_Responder")

Good_vs_Bad_Baseline <- DMR_DMP_analysis(BMIQ_norm_Koichi_samples, Good_Bad_Baseline_sample, Factor_Good_Bad_Baseline)
```

############ BASELINE vs CD34+

```{r}
Baseline_Control_sample <- c(Baseline_Sample, Control_Sample)
Factor_Baseline_Control <- colnames(BMIQ_norm_Koichi_samples)[colnames(BMIQ_norm_Koichi_samples) %in% Baseline_Control_sample]
Factor_Baseline_Control <- ifelse(Factor_Baseline_Control %in% Baseline_Sample, "Baseline", "Control")

Baseline_vs_Control <- DMR_DMP_analysis(BMIQ_norm_Koichi_samples, Baseline_Control_sample, Factor_Baseline_Control)
```

############ GOOD Post vs Control

```{r}
Good_Post_Control_sample <- c(intersect(Good_responder_Sample, Post_response_Sample), Control_Sample)
Factor_Good_Post_Control <- colnames(BMIQ_norm_Koichi_samples)[colnames(BMIQ_norm_Koichi_samples) %in% Good_Post_Control_sample]
Factor_Good_Post_Control <- ifelse(Factor_Good_Post_Control %in% Good_responder_Sample, "Good_Responder_Post", "Control")

Good_Post_vs_Control <- DMR_DMP_analysis(BMIQ_norm_Koichi_samples, Good_Post_Control_sample, Factor_Good_Post_Control)
```

############ Bad Post vs Control
```{r}
Bad_Post_Control <- c(intersect(Bad_responder_Sample, Post_response_Sample), Control_Sample)
Factor_Bad_Post_Control <- colnames(BMIQ_norm_Koichi_samples)[colnames(BMIQ_norm_Koichi_samples) %in% Bad_Post_Control]
Factor_Bad_Post_Control <- ifelse(Factor_Bad_Post_Control %in% Bad_responder_Sample, "Bad_Responder_Post", "Control")

Bad_Post_vs_Control <- DMR_DMP_analysis(BMIQ_norm_Koichi_samples, Bad_Post_Control, Factor_Bad_Post_Control)
```







